name: gerencia_de_projetos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.1.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

assets:
  - images/a_dot_burr.jpeg
  - images/a_dot_ham.jpeg

